apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fluentd-sidecar-role
  namespace: sidecar
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]

