apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: sidecar
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/nginx/access.log
      pos_file /var/log/fluent/nginx-access.log.pos
      tag nginx.access
      format nginx
    </source>

    <match nginx.access>
      @type forward
      send_timeout 60s
      recover_wait 10s
      heartbeat_interval 1s
      phi_threshold 8
      hard_timeout 60s
      <server>
        name sidecar
        host sidecar
        port 24224
      </server>
    </match>

