apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluentd-rolebinding
  namespace: sidecar
subjects:
  - kind: ServiceAccount
    name: fluentd-sidecar-account
    namespace: sidecar
roleRef:
  kind: Role
  name: fluentd-role
  apiGroup: rbac.authorization.k8s.io

