apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  namespace: sidecar
spec:
  serviceAccountName: fluentd-sidecar-account
  volumes:
    - name: log-volume
      emptyDir: {}
  containers:
    - name: main
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
    - name: sidecar
      image: busybox:1.28
      command: ["/bin/sh", "-c", "tail -f /var/log/nginx/access.log"]   # Correct command for tailing logs
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
  restartPolicy: Always

