apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo 'Container 1 is running...'; exit 1"]
      # Add an initial command that will cause the busybox container to fail initially.
      lifecycle:
        postStart:
          exec:
            command:
              - "sh"
              - "-c"
              - "sleep 1000"
    - name: redis
      image: redis
  restartPolicy: Always

