apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["sh", "-c", "sleep 1000"]
  - name: redis-container
    image: redis
  restartPolicy: Always

