apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as per your requirement
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector: # Node selector to ensure it runs only on nodes with "env=stage" label
        env: stage
      affinity: # Node affinity rule to ensure it runs only on nodes with "env=stage" label
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - stage
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

