apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mysql-pv

